[package]
name = "csscolorparser"
version = "0.2.0"
authors = ["Nor Khasyatillah <mazznoer@ymail.com>"]
edition = "2018"
description = "CSS color parser library"
readme = "README.md"
repository = "https://github.com/mazznoer/csscolorparser-rs"
documentation = "https://docs.rs/csscolorparser/"
license = "MIT OR Apache-2.0"
keywords = ["color", "colour", "css", "parser", "parse"]
categories = ["graphics", "parser-implementations"]
exclude = [
	".github/*",
	".travis.yml",
	"tests/*",
]

[dependencies]
phf = {version="0.8.0", features=["macros"]}
