[package]
name = "csscolorparser"
version = "0.4.0"
authors = ["Nor Khasyatillah <mazznoer@ymail.com>"]
edition = "2018"
description = "CSS color parser library"
readme = "README.md"
repository = "https://github.com/mazznoer/csscolorparser-rs"
documentation = "https://docs.rs/csscolorparser/"
license = "MIT OR Apache-2.0"
keywords = ["color", "colour", "css", "parser", "parse"]
categories = ["graphics", "parser-implementations"]
exclude = [
	".github/*",
	".travis.yml",
	"tests/*",
]

[features]
default = ["named-colors"]
named-colors = ["phf"]
rust-rgb = ["rgb"]

[dependencies]
phf = { version = "0.8.0", optional = true, features = ["macros"] }
rgb = { version = "0.8.25", optional = true }

